name: print slogan

on:
  workflow_dispatch:


jobs:
  print-slogan:
    runs-on: ubuntu-latest
    env:
      SLOGAN: "my slogan"
      
    steps:
        - name: Print Slogan
          run: echo $SLOGAN
    
